# Generated by Django 3.1.7 on 2021-03-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('date_of_employment', models.DateField(verbose_name='Дата приёма на работу')),
                ('salary', models.IntegerField()),
                ('department', models.CharField(max_length=150, verbose_name='Имя')),
                ('position', models.CharField(max_length=150, verbose_name='Имя')),
            ],
            options={
                'db_table': 'Работник',
            },
        ),
    ]
