# Generated by Django 3.1.7 on 2021-03-10 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employees',
            table=None,
        ),
    ]
