# Generated by Django 3.1.7 on 2021-03-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_employees', '0002_auto_20210310_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='rank',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ранг'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='date_of_employment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приёма на работу'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
