# Generated by Django 3.1.7 on 2021-03-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_employees', '0003_auto_20210315_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_of_employment',
            field=models.DateField(default='2021-01-01', verbose_name='Дата приёма на работу'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.CharField(default='***', max_length=150, verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='first_name',
            field=models.CharField(default='***', max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='last_name',
            field=models.CharField(default='***', max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='middle_name',
            field=models.CharField(default='***', max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(default='***', max_length=150, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='rank',
            field=models.CharField(default='***', max_length=150, verbose_name='Ранг'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(default=10),
        ),
    ]
