# Generated by Django 3.1.7 on 2021-03-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_employees', '0004_auto_20210315_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default='***', max_length=150, verbose_name='Департамент')),
                ('head', models.CharField(blank=True, max_length=150, null=True, verbose_name='Глава')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
