# Generated by Django 3.1.7 on 2021-03-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_employees', '0005_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department_name',
            field=models.CharField(default='***', max_length=150, unique=True, verbose_name='Департамент'),
        ),
    ]
